update versions

diff --git a/.github/actions/integration-test/action.yml b/.github/actions/integration-test/action.yml
--- a/.github/actions/integration-test/action.yml
+++ b/.github/actions/integration-test/action.yml
@@ -27,7 +27,7 @@ runs:
         export TEST_RUNNER_SERVER_SPECIFICATION_FILE=${{ inputs.test-server }}
         resultsDir=/tmp/results$RANDOM
         echo "Running test suite ${{ inputs.test }} on ${{ inputs.test-server }}"
-        ../gradlew :integration:runTest --args="${{ inputs.test }} $resultsDir" --scan || testResult=$? # Continue the script even if tests fail
+        ../gradlew :integration:runTest --args="${{ inputs.test }} $resultsDir" --scan && testResult=$? # Continue the script even if tests fail
         echo "Test result is $testResult"
         echo "Upload test results to Google Bucket"
         ../gradlew :integration:uploadResults --args="CompressDirectoryToTerraKernelK8S.json $resultsDir" --scan
